import React, { createContext, useState, useContext, useEffect } from 'react';

const translations = {
  ar: {
    dashboard: 'الرئيسية',
    orders: 'الطلبات',
    products: 'المنتجات',
    customers: 'العملاء',
    analytics: 'التحليلات',
    categories: 'الأقسام',
    search: 'ابحث هنا...',
    upgradeTitle: 'نسخة المحترفين',
    upgradeDesc: 'افتح الميزات المتقدمة وتتبع المبيعات بدقة.',
    getPro: 'الترقية الآن',
    admin: 'مدير',
    totalRevenue: 'إجمالي الإيرادات',
    totalSales: 'إجمالي المبيعات',
    recentOrders: 'أحدث الطلبات',
    viewAll: 'عرض الكل',
    topSelling: 'المنتجات الأكثر مبيعاً',
    orderId: 'رقم الطلب',
    productName: 'المنتج',
    customer: 'العميل',
    price: 'السعر',
    stock: 'المخزون',
    status: 'الحالة',
    actions: 'الإجراءات',
    productsInventory: 'مخزون المنتجات',
    manageCatalog: 'أدر كتالوج منتجاتك والمخزون والتسعير بكل أناقة.',
    addNewProduct: 'إضافة منتج جديد',
    searchProducts: 'البحث عن منتج بالاسم أو القسم...',
    advancedFilter: 'تصفية متقدمة',
    productDetails: 'تفاصيل المنتج',
    category: 'القسم',
    showing: 'عرض',
    of: 'من',
    previous: 'السابق',
    next: 'التالي',
    noProducts: 'لا توجد منتجات',
    couldntFind: 'لم نتمكن من العثور على أي شيء يطابق',
    revenueAnalytics: 'تحليلات الإيرادات',
    salesByCategory: 'المبيعات حسب القسم',
    pieces: 'قطعة',
    dashboardProductsAddNew: 'الرئيسية / المنتجات / إضافة جديد',
    discard: 'إلغاء',
    publishProduct: 'نشر المنتج',
    generalInformation: 'معلومات عامة',
    productNameInput: 'اسم المنتج',
    description: 'الوصف',
    pricing: 'التسعير',
    basePrice: 'السعر الأساسي',
    discount: 'الخصم',
    tax: 'الضريبة',
    inventory: 'المخزون',
    sku: 'رمز التخزين (SKU)',
    barcode: 'الباركود',
    quantity: 'الكمية',
    media: 'الوسائط / الصور',
    dragAndDrop: 'اسحب وإفلت الصورة هنا أو انقر للتصفح',
    categoryStatus: 'القسم والحالة',
    statusDraft: 'مسودة',
    statusPublished: 'منشور',
    editProduct: 'تعديل المنتج',
    delete: 'حذف',
    backToProducts: 'العودة للمنتجات',
    productInfo: 'معلومات المنتج',
    pricingDetails: 'تفاصيل التسعير',
    discountedPrice: 'السعر بعد الخصم',
    profitMargin: 'هامش الربح',
    inventoryStatus: 'حالة المخزون',
    skuLabel: 'رمز التخزين (SKU)',
    barcodeLabel: 'الباركود',
    stockLevel: 'مستوى المخزون الحالي',
    productImage: 'صورة المنتج',
    productMetadata: 'بيانات المنتج',
  },
  en: {
    dashboard: 'Dashboard',
    orders: 'Orders',
    products: 'Products',
    customers: 'Customers',
    analytics: 'Analytics',
    categories: 'Categories',
    search: 'Search here...',
    upgradeTitle: 'Upgrade to PRO',
    upgradeDesc: 'Unlock advanced analytics & elegant dashboard.',
    getPro: 'Get Pro',
    admin: 'Admin',
    totalRevenue: 'Total revenue',
    totalSales: 'Total Sales',
    recentOrders: 'Recent Orders',
    viewAll: 'View All',
    topSelling: 'Top Selling Products',
    orderId: 'Order ID',
    productName: 'Product Name',
    customer: 'Customer',
    price: 'Price',
    stock: 'Stock',
    status: 'Status',
    actions: 'Actions',
    productsInventory: 'Products Inventory',
    manageCatalog: 'Manage your catalog, stock, and pricing elegantly.',
    addNewProduct: 'Add New Product',
    searchProducts: 'Search products by name or category...',
    advancedFilter: 'Advanced Filter',
    productDetails: 'Product Details',
    category: 'Category',
    showing: 'Showing',
    of: 'of',
    previous: 'Previous',
    next: 'Next',
    noProducts: 'No products found',
    couldntFind: 'We couldn\'t find anything matching',
    revenueAnalytics: 'Revenue Analytics',
    salesByCategory: 'Sales by Category',
    pieces: 'pcs',
    dashboardProductsAddNew: 'Dashboard / Products / Add New',
    discard: 'Discard',
    publishProduct: 'Publish Product',
    generalInformation: 'General Information',
    productNameInput: 'Product Name',
    description: 'Description',
    pricing: 'Pricing',
    basePrice: 'Base Price',
    discount: 'Discount',
    tax: 'Tax',
    inventory: 'Inventory',
    sku: 'SKU',
    barcode: 'Barcode',
    quantity: 'Quantity',
    media: 'Media / Images',
    dragAndDrop: 'Drag and drop your image here or click to browse',
    categoryStatus: 'Category & Status',
    statusDraft: 'Draft',
    statusPublished: 'Published',
    editProduct: 'Edit Product',
    delete: 'Delete',
    backToProducts: 'Back to Products',
    productInfo: 'Product Info',
    pricingDetails: 'Pricing Details',
    discountedPrice: 'Discounted Price',
    profitMargin: 'Profit Margin',
    inventoryStatus: 'Inventory Status',
    skuLabel: 'SKU',
    barcodeLabel: 'Barcode',
    stockLevel: 'Current Stock Level',
    productImage: 'Product Image',
    productMetadata: 'Product Metadata',
  }
};

export const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('ar');

  useEffect(() => {
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  }, [lang]);

  const toggleLang = () => {
    setLang(prev => prev === 'ar' ? 'en' : 'ar');
  };

  const t = (key) => translations[lang][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
