const today = new Date().toISOString().split('T')[0];

export const ordersList = [
  { 
    id: "#ORD-10234", 
    customerId: 1,
    vendorId: 1,
    driverId: 1,
    customer: "Ahmed Hassan", 
    date: "2026-04-20", 
    amount: 120.00, 
    status: "Delivered", 
    paymentMethod: "Credit Card",
    paymentStatus: "Verified",
    paymentScreenshotUrl: "https://images.unsplash.com/photo-1554224155-1696413565d3?w=400&h=600&fit=crop",
    distanceKm: 4,
    deliveryFee: 20,
    driverFee: 15,
    platformCommission: 12,
    vendorAmount: 88,
    isCompleted: true,
    isPaid: true,
    settlementDate: "2026-04-20"
  },
  { 
    id: "#ORD-10235", 
    customerId: 2,
    vendorId: 2,
    driverId: 2,
    customer: "Sarah Ali", 
    date: today, 
    amount: 85.50, 
    status: "Pending", 
    paymentMethod: "Bank Transfer",
    paymentStatus: "Pending Verification",
    paymentScreenshotUrl: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=400&h=600&fit=crop",
    distanceKm: 2,
    deliveryFee: 10,
    driverFee: 8,
    platformCommission: 8.55,
    vendorAmount: 66.95,
    isCompleted: false,
    isPaid: false,
    settlementDate: null
  },
  { 
    id: "#ORD-10236", 
    customerId: 3,
    vendorId: 1,
    driverId: 1,
    customer: "John Doe", 
    date: today, 
    amount: 210.00, 
    status: "Delivered", 
    paymentMethod: "Bank Transfer",
    paymentStatus: "Pending Verification",
    paymentScreenshotUrl: "https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=400&h=600&fit=crop",
    distanceKm: 6,
    deliveryFee: 30,
    driverFee: 22,
    platformCommission: 21.00,
    vendorAmount: 167,
    isCompleted: true,
    isPaid: false,
    settlementDate: null
  },
  { 
    id: "#ORD-10237", 
    customerId: 1,
    vendorId: 2,
    driverId: 1,
    customer: "Ahmed Hassan", 
    date: today, 
    amount: 45.00, 
    status: "Cancelled", 
    paymentMethod: "Credit Card",
    paymentStatus: "Rejected",
    paymentScreenshotUrl: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=400&h=600&fit=crop",
    distanceKm: 3,
    deliveryFee: 15,
    driverFee: 0,
    platformCommission: 0,
    vendorAmount: 0,
    isCompleted: false,
    isPaid: false,
    settlementDate: null
  },
  { 
    id: "#ORD-10238", 
    customerId: 2,
    vendorId: 3,
    driverId: 2,
    customer: "Michael Brown", 
    date: today, 
    amount: 150.00, 
    status: "Delivered", 
    paymentMethod: "Cash",
    paymentStatus: "Verified",
    paymentScreenshotUrl: null,
    distanceKm: 5,
    deliveryFee: 25,
    driverFee: 18,
    platformCommission: 15,
    vendorAmount: 117,
    isCompleted: true,
    isPaid: true,
    settlementDate: today
  },
  { 
    id: "#ORD-10239", 
    customerId: 1,
    vendorId: 1,
    driverId: 1,
    customer: "Layla Hassan", 
    date: today, 
    amount: 75.20, 
    status: "Delivered", 
    paymentMethod: "Credit Card",
    paymentStatus: "Verified",
    paymentScreenshotUrl: null,
    distanceKm: 2,
    deliveryFee: 10,
    driverFee: 8,
    platformCommission: 7.52,
    vendorAmount: 59.68,
    isCompleted: true,
    isPaid: false,
    settlementDate: null
  }
];
